### ISSUE TITLE
Should be Microsoft 365 "apps" for enterprise%  and not Microsoft 365 for enterprise% Line 178

### ISSUE THREAD

**Issue by Mrgreen17** [gwblok/garytown#1]
https://github.com/gwblok/garytown/blob/8f518132d5450f02783ddf9974586af7d32617ab/Office365/o365_install.ps1#L178

![image](https://user-images.githubusercontent.com/43708957/127504188-5d82814d-f9e6-4ecb-a0bb-bf58eb851dc9.png)

**Comment by gwblok** [comment]
Thanks, that has been resolved
