### ISSUE TITLE
Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Version".

### ISSUE THREAD

**Issue by JamesHeathcote** [gwblok/garytown#12]
Running the latest version of the detect script 23.3.9.1, receive the following errors.

Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Version".
At C:\Users\xxx\Desktop\Update-DellApps-Detect.ps1:235 char:24
+ ... InstalledDCU){[Version]$DCU_InstalledVersion = $InstalledDCU.Version}
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException
 
WARNING: Name resolution of proxy-recastsoftware.com failed
No Proxy Server Found, continuing without
Downloading Dell Cab
VERBOSE: GET with 0-byte payload
VERBOSE: received 284281-byte response of content type application/vnd.ms-cab-compressed
Expanding the Cab File...
Loading Dell Catalog XML..
VERBOSE: GET with 0-byte payload
VERBOSE: received 231375-byte response of content type application/vnd.ms-cab-compressed
Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Version".
At C:\Users\xxx\Desktop\Update-DellApps-Detect.ps1:315 char:32
+ ...  If ($InstalledDCU){[Version]$CurrentVersion = $InstalledDCU.Version}
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException
 
Could not compare "10.9.1.11" to "". Error: "Cannot convert value "" to type "System.Version". Error: "Version string portion was too short or too long.""
At C:\Users\xxx\Desktop\Update-DellApps-Detect.ps1:404 char:17
+             if ($DCMVersion -gt $CurrentVersion)
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : ComparisonFailure
 
Non-Compliant, Exit 1, to trigger Remediation to Update Software

**Comment by JamesHeathcote** [comment]
[Dell-Updates.log](https://github.com/gwblok/garytown/files/11871903/Dell-Updates.log)

**Comment by gwblok** [comment]
This should be resolved now.
Guessing when I last tested this script, It wasn't on a machine without any versions installed, so that test scenario didn't get covered.
Note, I have 1 Dell machine (Optiplex 7050), so I don't do extensive testing.  I really would like someone from Dell to take over ownership of this idea and support it.
In the future, I recommend buying HP devices if you'd like quicker support. 

![image](https://github.com/gwblok/garytown/assets/26312309/9a45f225-28eb-4f4b-bc64-bff0922f91a7)

**Comment by gwblok** [comment]
Considered closed
