### ISSUE TITLE
Winget

### ISSUE THREAD

**Issue by DevRWC2023** [gwblok/garytown#13]
Afternoon So myself and a fellow worker are busy working on OSD Cloud and would like to find out if there is any possibility of incorporating Winget into the Task sequence.
At the same time is there away to speed up the curl download for the OS.

**Comment by AkosBakos** [comment]
What is your exact use case for WinGet integration?

The download process is dependent on your ISP line and the FW infra. If you wish, you can put your OS wim/esd into the WinPE media.

**Comment by DevRWC2023** [comment]
Afternoon. Well for the winget integration it would assist in installing apps. Instead of using NineNite. With the winget it will give us the opportunity to download the latest software and repository. We are wanting to use OSDcloud for a student environment.

**Comment by DevRWC2023** [comment]
Is there perhaps a Powershell script that I can add to the ts to pull apps from Intune. That would also help instead of winget
Thank you again for the Responce appreciate what you all do

**Comment by gwblok** [comment]
WinGet is completely separate.  You can integrate it yourself into a ConfigMgr Task Sequence, or OSDCloud using Setup Complete scripts.

I'd suggest writing your own PS Script that setups WinGet, then installs your apps.  Once you have a working script, you can start to incorporate it into your OSD process.

As for installing apps from intune, that's not possible during OSD as it would require the device joined to Entra (Azure AD), and / or the user having rights in Entra to authenticate and pull down the Apps.

If you have Intune, you're best bet is to set your machines to AutoPilot, then have AP take over the app install process pulling content from Intune.
