### ISSUE TITLE
Add detection of internal hard drives, both nvme M.2 SSDs, SATA SSDs, and SATA HDDs to OSDCloud GUI

### ISSUE THREAD

**Issue by osdcloudcline** [gwblok/garytown#17]
In a future version of OSDCloud, somehow add in to the GUI an extra combo box, that would list the installed physical drives. Possibly add in some type of detection methodology to display disk number and drive info (manufacturer, model and size). Maybe even a secondary combo box to choose the drive letter as well. Then somehow pass those onto PS Module, when Start-OSDCloudGUI starts the deployment of the OS.

**Comment by gwblok** [comment]
Moved to OSDCloud's GitHub, closing here
