### ISSUE TITLE
EDL List of IPs

### ISSUE THREAD

**Issue by DevRWC2023** [gwblok/garytown#18]
Hello there.
I would like to find out is there perhaps an edl list of IP's which I can use to apply to the firewall. As it seems everytime I get the system working the ip ranges change and I have to hunt for new Ip ranges. To get OSD cloud to work. Through the Palo firewall. The reason for me asking it's seems on a weekly basis I have to go hunt for a new ip address. As this time the only issue I am having is the connection getting closed for curl. I have picked up an additional 3 iOS I need to add to the firewall to allow connections. An EDL list of IPs would be great if it's possible. Thank you

**Comment by gwblok** [comment]
OSDCloud uses URLs from:
Microsoft, Dell, Lenovo, Intel, HP.

I'd recommend putting as much content as possible on the OSDCloud USB flash drive, so it doesn't need to make many if any connections to the internet during the process.
