### ISSUE TITLE
Schedule the time

### ISSUE THREAD

**Issue by horst789github** [gwblok/garytown#2]
Hi,

thanks for nice work! 
I want to try to add time/date Parameter for a schedule start of the task sequence. But i dont see in the code where i can set the time, have you an idea?

is this the ADV_ProgramWindowStartTime Value ?

**Comment by gwblok** [comment]
Sorry, I just noticed this issue.  I honestly haven't ever tried to change the schedule on it. Unsure if it is even possible.  Please let me know if you've figured it out since you first asked this question.
