### ISSUE TITLE
TaskSequenceSteps2Excel | BootImage2Excel.ps1 - null-valued expression

### ISSUE THREAD

**Issue by yafp** [gwblok/garytown#6]
I was going to test both:

- BootImage2Excel.ps1
- TS2Excelv2.ps1
- 
In both cases i started without providing parameters and then inputted them interactive in the dialog

Both scripts fails for me with a:
>> You cannot call a method on a null-valued expression error

Example from BootImage2Excel.ps1
![2022-02-18 14_20_05-2022-02-18 14_17_22_ts2excel](https://user-images.githubusercontent.com/67605/154690735-8626666f-088c-4108-96c7-ce6e3b704fdc.png)

Any idea what i might be missing here?

**Comment by gwblok** [comment]
Sorry for asking obvious before I look into this more, you are running the script on a machine that has the CM Console PowerShell Commandlets and MS Excel installed?

**Comment by yafp** [comment]
Hi gwblok,

I'll check once again and will report back

**Comment by gwblok** [comment]
Still working for me... if anyone has an issue, please open a new issue
