### ISSUE TITLE
Update-DellApps-Detect.ps1 | Cannot convert System.Object to System.Version 

### ISSUE THREAD

**Issue by heino-vdbh** [gwblok/garytown#7]
If I run Update-DellApps-Detect.ps1 I get the following error message but the Dell Command | Monitor was installed.

-----------

<![LOG[error from script =Der Wert "System.Object[]" vom Typ "System.Object[]" kann nicht in den Typ "System.Version" konvertiert werden.
In C:\WINDOWS\IMECache\HealthScripts\8bca1ee6-4593-40dc-ab38-85e673f41f47_1\detect.ps1:296 Zeichen:13
+             [Version]$DCUVersion = $DellItem.vendorVersion
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException
 
Get-Date : "System.Object[]" kann nicht in den Typ "System.DateTime" konvertiert werden, der für den Parameter "Date" 
erforderlich ist. Die angegebene Methode wird nicht unterstützt.
In C:\WINDOWS\IMECache\HealthScripts\8bca1ee6-4593-40dc-ab38-85e673f41f47_1\detect.ps1:297 Zeichen:42
+ ...            $DCUReleaseDate = $(Get-Date $DellItem.releaseDate -Format ...
+                                             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Date], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.GetDateCommand
 

]LOG]!>

[Dell-Updates.log](https://github.com/gwblok/garytown/files/8251835/Dell-Updates.log)

**Comment by patrickpouw** [comment]
The problem in the script is that on line 284 and 285 it returns 2 applications

PS > $AppDCU

schemaVersion             : 3.0
releaseID                 : 601KT
releaseDate               : April 01, 2022
vendorVersion             : 4.5.0
dellVersion               : A00
packageType               : LWXP
path                      : FOLDER08334704M/2/Dell-Command-Update-Windows-Universal-Application_601KT_WIN_4.5.0_A00_01.EXE
packageID                 : 601KT
dateTime                  : 2022-01-06T13:10:24+05:30
size                      : 33455904
identifier                : c1a89389-6a1a-4926-b3b9-7c77e676d9c1
Name                      : Name
ComponentType             : ComponentType
Description               : Description
Category                  : Category
SupportedDevices          : SupportedDevices
SupportedSystems          : SupportedSystems
SupportedOperatingSystems : SupportedOperatingSystems
ImportantInfo             : ImportantInfo
Criticality               : Criticality
Cryptography              : Cryptography
SharedModules             : SharedModules

schemaVersion             : 3.0
releaseID                 : W4HP2
releaseDate               : March 24, 2022
vendorVersion             : 4.5.0
dellVersion               : A00
packageType               : LWXP
path                      : FOLDER08334841M/4/Dell-Command-Update-Application_W4HP2_WIN_4.5.0_A00_02.EXE
packageID                 : W4HP2
dateTime                  : 2022-01-06T13:13:39+05:30
size                      : 31297992
identifier                : 095db0f2-3c9d-4694-a418-fdcedfd3e9aa
Name                      : Name
ComponentType             : ComponentType
Description               : Description
Category                  : Category
SupportedDevices          : SupportedDevices
SupportedSystems          : SupportedSystems
SupportedOperatingSystems : SupportedOperatingSystems
ImportantInfo             : ImportantInfo
Criticality               : Criticality
Cryptography              : Cryptography
SharedModules             : SharedModules

I've changed both lines where it says 'command-update' to 'Command-Update-Windows' and script is now working as it should

**Comment by gwblok** [comment]
Sorry for Delay, been busy on other projects and totally forgot.
Resolved the issue with it hot finding DCU to install
