### ISSUE TITLE
Fix line 71 in o365_download.ps1 to $NewFolder = New-Item -Path $ODTExtractPath -ItemType Directory -Force

### ISSUE THREAD

**Issue by Mrgreen17** [gwblok/garytown#9]
Fix line 71 in o365_download.ps1 to $NewFolder = New-Item -Path $ODTExtractPath -ItemType Directory -Force

the original line is $NewFolder = New-Item -Path $OSDExtractPath -ItemType Directory -Force

and it needs to be 

$NewFolder = New-Item -Path $ODTExtractPath -ItemType Directory -Force

**Comment by gwblok** [comment]
Thanks

**Comment by gwblok** [comment]
Done, thank you!

**Comment by gwblok** [comment]
Done
